// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Comment struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Body      string
	PostID    string
	UserID    string
}

type Post struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Header    string
	Body      string
	Tag       string
	UserID    string
}

type User struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Username  string
	Password  string
	ApiKey    string
}

type VotedComment struct {
	ID        string
	CommentID string
	UserID    string
}

type VotedPost struct {
	ID     string
	PostID string
	UserID string
}
